### ISSUE TITLE
Minimist <=1.2.5 is vulnerable to Prototype Pollution

### ISSUE THREAD

**Issue by Cordazar** [darkobits/vite-plugin-favicons#11]
Minimist <=1.2.5 is vulnerable to Prototype Pollution via file index.js, function setKey() (lines 69-95).

https://github.com/advisories/GHSA-xvch-5gv4-984h

**Comment by darkobits** [comment]
Updated dependencies; as of [v0.2.0](https://github.com/darkobits/vite-plugin-favicons/tree/v0.2.0) this package no longer has versions of minimist <= 1.2.5 in its dependency graph.
